services:
  postgres:
    image: 'postgres:16-alpine'
    command: postgres -c timezone='UTC' -c log_timezone='UTC'
    environment:
      - 'POSTGRES_DB=booky_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
      - 'TZ=UTC'
      - 'PGTZ=UTC'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql'

volumes:
  postgres_data:
